Fixed up mispaste.

diff --git a/.github/workflows/release-check.yml b/.github/workflows/release-check.yml
--- a/.github/workflows/release-check.yml
+++ b/.github/workflows/release-check.yml
@@ -20,36 +20,26 @@ jobs:
             latest_url=""
             for i in `seq 1 10`; do
                 latest_url=$(curl -s https://api.github.com/repos/${{github.repository}}/releases/latest | grep '.tar.gz' |  grep browser_download_url | awk '{print $2}' | sed -e 's/\"//g')
-                backup_url=$(curl -s https://api.github.com/repos/${{github.repository}}/releases/latest | jq ".browser_download_url")
                 if [ "x$latest_url" != "x" ]; then
-                  break;
+                  echo "Pulling down Santa from URL: $latest_url"
+                  curl -s -L -o santa.tar.gz $latest_url
+                  # expand the installer
+                  tar zxf ./santa.tar.gz
+                  exit 0
                 fi
             done;
 
-            if [ "x$latest_url" == "x" ]; then
-              echo "unable to get url"
-              echo "backup_url: $backup_url"
-              exit 1;
-            fi
-
-            echo "Pulling down Santa from URL: $latest_url"
-            if [ "x$latest_url" == "x" ]; then
-              echo "backup_url: $backup_url"
-
-            fi
-            echo "Pulling down Santa from URL: $latest_url"
-
-            curl -s -L -o santa.tar.gz $latest_url
-
-            # expand the installer
-            tar zxf ./santa.tar.gz
+            echo "unable to get url for ${GITHUB_REF#refs/*/}"
+            echo "JSON: $(curl -s https://api.github.com/repos/${{github.repository}}/releases/latest)"
+            exit 1;
 
        - name: "Check Santa.App Codesigning" 
          run: |
             cd santa-*/Conf
+            BINS=('Santa' 'santabundleservice' 'santactl')
 
-            for $bin in "Santa\nsantabundleservice\nsantactl"; do
-              codesign --verify --verbose
+            for bin in "${BINS[@]}"; do
+              codesign --verify --verbose ./Santa.app/Contents/MacOS/$bin
               codesign -d -vvv ./Santa.app/Contents/MacOS/$bin
             done
 
